### ISSUE TITLE
Size is not same for all images in opennebula

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/vertice#175]
When we upload images to production server, we shall change all image size to 10GB.
Sample Command : 
```
qemu-img resize coreos_production_qemu_image.img +4Gb
```

**Comment by indykish** [comment]
@thomasalrin  Should we fix something in megamd for this ? If its a doc thing, then move it our docs.megam.io ?

**Comment by thomasalrin** [comment]
@indykish, it is a doc thing. We can resize our images and then upload them in s3. Users can also resize them, if they want.

**Comment by indykish** [comment]
Doc and close it then.

**Comment by indykish** [comment]
Dup of  #219
