### ISSUE TITLE
Torpedo CoreOS upate IP in assembly 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/vertice#211]
Because coreos cannot run gulpd

**Comment by vijaykanthm28** [comment]
CONTEXT=[FILES="/megam/init.sh",GATEWAY="$NETWORK[GATEWAY, NETWORK=\"open-vs\"]",HOSTNAME="megamcore",IP_ADDRESS="$NIC[IP, NETWORK=\"open-vs\"]",NETWORK="YES",SSH_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1jQliF7Nl3tQ6fPcbSy4MD8bsmDrYkkhxND3jI26ckNxapdiq7ujeU9bFS8ttZB495F9fMHiY0s344FqKLtyTOVogmUesT3ysO2h87iTDN3bkcXL6I3bE5oxlRtlSt9QNygzBR9B7BMerYRkQqTQZwxTu+ETb9Nu+5pBKRXlDHSNssFuhD/8t4ZpLzws+vSYMxpFWnTyIAqZ33oZUl8MK+j5gP77+WRgBByAqztjDO+gP4Wq2Qmj/IIG1L4/z3ZTq2wAkahNIykH8PgKEpLzYL8XSEPo09JAXw+UpEWPyzyway/f35zaNkV15naUBfwQMXhWYL0UjJ7ol7FOn8tR7 oneadmin@megammaster"]
CPU="0.3"
DESCRIPTION="Coreos image test"
DISK=[IMAGE="coreos",IMAGE_UNAME="oneadmin"]
GRAPHICS=[LISTEN="0.0.0.0",TYPE="vnc"]
MEMORY="768"
NIC=[NETWORK="open-vs",NETWORK_UNAME="oneadmin"]
OS=[ARCH="x86_64"]

**Comment by vijaykanthm28** [comment]
@indykish fixed in gulpd

**Comment by indykish** [comment]
@vijaykanthm28  Good job.
