### ISSUE TITLE
vertice cannot create VM stuck in create carton

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/vertice#212]
time="2016-02-11T15:08:37+05:30" level=debug msg="\x1b[1;34;10m  > [riak] open  \x1b[0m[192.168.1.105:8087] success" 
time="2016-02-11T15:08:37+05:30" level=debug msg="\x1b[1;34;10m  > [riak] fetch\x1b[0m (assemblies, AMS1309500731711160320)" 
time="2016-02-11T15:08:37+05:30" level=debug msg="\x1b[1;34;10m  > [riak] close\x1b[0m" 
time="2016-02-11T15:08:37+05:30" level=debug msg="Assemblies id: AMS1309500731711160320\naccountsid: ACT1303328067044900864\njsonclaz: Megam::Assemblies\nname: \"\"\nassemblysid:\n- ASM1309500731685994496\ninputs: []\ncreatedat: 2016-02-11 09:38:37 +0000\n" 
time="2016-02-11T15:08:37+05:30" level=debug msg="\x1b[1;34;10m  > [riak] open  \x1b[0m[192.168.1.105:8087] success" 
time="2016-02-11T15:08:37+05:30" level=debug msg="\x1b[1;34;10m  > [riak] fetch\x1b[0m (assembly, ASM1309500731685994496)" 
time="2016-02-11T15:08:37+05:30" level=debug msg="\x1b[1;34;10m  > [riak] close\x1b[0m" 
time="2016-02-11T15:08:37+05:30" level=debug msg="Cartons [id: ASM1309500731685994496\nname: directing\ncartonsid: AMS1309500731711160320\ntosca: tosca.torpedo.coreos\nimageversion: 835.12.0\ncompute:\n  cpushare: \"0.5\"\n  memory: \"896\"\n  swap: \"\"\n  hdd: \"10\"\nssh:\n  user: megam\n  prefix: vijaykanth@megam.io_second\ndomainname: megambox.com\nprovider: one\npublicip: \"\"\nboxes:\n- id: ASM1309500731685994496\n  cartonsid: AMS1309500731711160320\n  cartonid: ASM1309500731685994496\n  cartonname: directing\n  name: directing\n  level: 4\n  domainname: megambox.com\n  tosca: tosca.torpedo.coreos\n  imageversion: 835.12.0\n  compute:\n    cpushare: \"0.5\"\n    memory: \"896\"\n    swap: \"\"\n    hdd: \"10\"\n  repo: null\n  status: launching\n  provider: one\n  publicip: \"\"\n  ssh:\n    user: \"\"\n    prefix: \"\"\n  commit: \"\"\n  envs: []\n  address: null\nstatus: launching\n]" 
time="2016-02-11T15:08:37+05:30" level=debug msg="\x1b[1;36;10mCREATE CARTON AMS1309500731711160320\x1b[0m" 
time="2016-02-11T15:08:37+05:30" level=debug msg="\x1b[1;36;10mdirecting.megambox.com\x1b[0m in (\x1b[1;32;10m45.395µs\x1b[0m)\n\x1b[0;33;10m\x1b[0m"

**Comment by thomasalrin** [comment]
Fix it first as it is a sev1 problem.

**Comment by vijaykanthm28** [comment]
@thomasalrin #212 bug fixed

**Comment by indykish** [comment]
@vijaykanthm28  Good job.
