### ISSUE TITLE
when launch torpedo the update status  assembly missing 

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/vertice#218]
-- ks &gocassa.k{qe:gocassa.goCQLBackend{session:(*gocql.Session)(0xc820143440)}, name:"vertice", debugMode:false, tableFactory:(*gocassa.k)(0xc8203a4200)}time="2016-03-09T15:46:08+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] fetch\x1b[0m (assembly, %!s(MISSING))" 
time="2016-03-09T15:46:08+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] table assembly\x1b[0m" 
time="2016-03-09T15:46:08+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] read\x1b[0m" 
SELECT created_at, inputs, outputs, policies, status, tosca_type, components, id, org_id, name, json_claz FROM vertice.assembly  WHERE id = ? ALLOW FILTERING [ASM8552871150452116431]
time="2016-03-09T15:46:08+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] keyspace vertice\x1b[0m" 
-- ks &gocassa.k{qe:gocassa.goCQLBackend{session:(*gocql.Session)(0xc82009b680)}, name:"vertice", debugMode:false, tableFactory:(*gocassa.k)(0xc8203dc640)}time="2016-03-09T15:46:08+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] fetch\x1b[0m (assembly, %!s(MISSING))" 
time="2016-03-09T15:46:08+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] table assembly\x1b[0m" 
time="2016-03-09T15:46:08+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] update\x1b[0m" 
UPDATE vertice.assembly SET Inputs = ?, Status = ? WHERE id = ? AND org_id = ? [[{"key":"domain","value":"megambox.com"} {"key":"sshkey","value":"rr"} {"key":"provider","value":"one"} {"key":"cpu","value":"1 Core"} {"key":"ram","value":"1 GB"} {"key":"hdd","value":"24 GB SSD"} {"key":"version","value":"14.04"} {"key":"status","value":"launched"} {"key":"lastsuccessstatusupdate","value":"09 Mar 16 15:46 IST"}] launched ASM8552871150452116431 ORG8430926729513576530]
time="2016-03-09T15:46:08+05:30" level=debug msg="\x1b[1;32;10m  => step 3: deduct-cons-machine action\x1b[0m" 
time="2016-03-09T15:46:08+05:30" level=debug msg="citizenry.megambox.com_log:{09 Mar 16 15:46 IST   update status for machine (citizenry.megambox.com, launching) OK megd citizenry ASM8552871150452116431}" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5cd5e4]

goroutine 355 [running]:
github.com/megamsys/vertice/events.(*EventsWriter).Write(0x0, 0xc82024c190, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/events/writer.go:55 +0x24
github.com/megamsys/vertice/events.(*MultiEvent).Write(0xc820481138, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/events/info.go:133 +0x11a
github.com/megamsys/vertice/provision/one/machine.(*Machine).Deduct(0xc82045e750, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/machine/machine.go:94 +0x2b8
github.com/megamsys/vertice/provision/one.glob.func5(0xd52500, 0xc82045e510, 0xc820405910, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/actions.go:130 +0x392
github.com/megamsys/libgo/action.(*Pipeline).Execute(0xc820402400, 0xc820405910, 0x1, 0x1, 0x0, 0x0)
	/home/ranjitha/.go/src/github.com/megamsys/libgo/action/action.go:147 +0xc3d
github.com/megamsys/vertice/provision/one.(*oneProvisioner).deployPipeline(0xc82012fec0, 0xc8203a0b00, 0xc8204058c0, 0xc, 0x7f516e10c4a8, 0xc820402320, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/provisioner.go:169 +0x3f0
github.com/megamsys/vertice/provision/one.(*oneProvisioner).ImageDeploy(0xc82012fec0, 0xc8203a0b00, 0xc8204058c0, 0xc, 0x7f516e10c4a8, 0xc820402320, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/provisioner.go:140 +0x36d
github.com/megamsys/vertice/carton.deployToProvisioner(0xc82036c0a8, 0x7f516e10c4a8, 0xc820402320, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/deploy.go:74 +0x202
github.com/megamsys/vertice/carton.Deploy(0xc82036c0a8, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/deploy.go:59 +0x2c1
github.com/megamsys/vertice/carton.(*Carton).Deploy(0xc8203a2fc0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/carton.go:75 +0x11d
github.com/megamsys/vertice/carton.CreateProcess.Process(0xc82037a800, 0x16, 0xc820134168, 0x1, 0x1, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/megd_process.go:37 +0x74
github.com/megamsys/vertice/carton.(*CreateProcess).Process(0xc820242d20, 0xc820134168, 0x1, 0x1, 0x0, 0x0)
	<autogenerated>:3 +0xc2
github.com/megamsys/vertice/carton.(*ReqOperator).Accept(0xc820481f38, 0xc820481f08, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/req_operator.go:41 +0x1a7
github.com/megamsys/vertice/subd/deployd.(*Handler).serveNSQ(0xc8201d1780, 0xc820246720, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/subd/deployd/handler.go:24 +0x150
created by github.com/megamsys/vertice/subd/deployd.(*Service).processNSQ
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/subd/deployd/service.go:74 +0xc8

**Comment by indykish** [comment]
A known issue when you have turned off events, `vertice barfs`. We need to skip it.

**Comment by indykish** [comment]
@ranjithamca check this fix in testing tomorrow.
