### ISSUE TITLE
template in rpc the value must be numeric

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/vertice#219]
UPDATE vertice.assembly SET Inputs = ?, Status = ? WHERE id = ? AND org_id = ? [[{"key":"domain","value":"megambox.com"} {"key":"sshkey","value":"rr"} {"key":"provider","value":"one"} {"key":"cpu","value":"1 Core"} {"key":"ram","value":"1 GB"} {"key":"hdd","value":"24 GB SSD"} {"key":"version","value":"14.04"} {"key":"lastsuccessstatusupdate","value":"09 Mar 16 16:25 IST"} {"key":"status","value":"launching"}] launching ASM5691498491739602968 ORG8430926729513576530]
time="2016-03-09T16:25:50+05:30" level=debug msg="\x1b[1;32;10m  => step 1: create-machine action\x1b[0m" 
time="2016-03-09T16:25:50+05:30" level=info msg="  creating machine in one (bode.megambox.com, ubuntu_14.04)" 
time="2016-03-09T16:25:50+05:30" level=debug msg="\x1b[1;34;10m  > [one-go] connecting\x1b[0m" 
time="2016-03-09T16:25:50+05:30" level=debug msg="\x1b[1;34;10m  > [one-go] connected\x1b[0m http://192.168.1.105:2633/RPC2" 
time="2016-03-09T16:25:50+05:30" level=debug msg="\x1b[1;34;10m  > [one-go] \x1b[0mone.templatepool.info" 
time="2016-03-09T16:25:50+05:30" level=debug msg="\x1b[1;36;10m\n> args   \x1b[0m [oneadmin:yourWuOtHij3 -2 -1 -1]\n" 
time="2016-03-09T16:25:50+05:30" level=debug msg="bode.megambox.com_log:{09 Mar 16 16:25 IST   update status for machine (bode.megambox.com, launching) OK megd bode ASM5691498491739602968}" 
ERR    6 (103.56.92.4:4150) IO error - EOF
time="2016-03-09T16:25:50+05:30" level=debug msg="bode.megambox.com_log:{09 Mar 16 16:25 IST   create machine for box (bode.megambox.com, image:ubuntu_14.04)/{1 Core 1 GB  24 GB SSD} megd bode ASM5691498491739602968}" 
ERR    7 (103.56.92.4:4150) IO error - EOF
time="2016-03-09T16:25:50+05:30" level=debug msg="\x1b[1;34;10m  > [one-go] ( ´ ▽ ` ) SUCCESS\x1b[0m" 
time="2016-03-09T16:25:50+05:30" level=debug msg="\x1b[1;34;10m  > [one-go] \x1b[0mone.template.instantiate" 
time="2016-03-09T16:25:50+05:30" level=debug msg="\x1b[1;36;10m\n> args   \x1b[0m [oneadmin:yourWuOtHij3 32 bode.megambox.com false <Template><CONTEXT><NETWORK>YES</NETWORK><FILES>/megam/init.sh</FILES><SSH_PUBLIC_KEY></SSH_PUBLIC_KEY><SET_HOSTNAME>$NAME</SET_HOSTNAME><NODE_NAME>$NAME</NODE_NAME><ACCOUNTS_ID></ACCOUNTS_ID><PLATFORM_ID></PLATFORM_ID><ASSEMBLY_ID>ASM5691498491739602968</ASSEMBLY_ID><ASSEMBLIES_ID>AMS7575906295965235998</ASSEMBLIES_ID></CONTEXT><CPU>1 Core</CPU><CPU_COST>5</CPU_COST><DESCRIPTION>test trusty image</DESCRIPTION><HYPERVISOR></HYPERVISOR><LOGO></LOGO><MEMORY>1 GB</MEMORY><MEMORY_COST>10</MEMORY_COST><SUNSTONE_CAPACITY_SELECT></SUNSTONE_CAPACITY_SELECT><SUNSTONE_NETWORK_SELECT></SUNSTONE_NETWORK_SELECT><VCPU></VCPU><GRAPHICS><LISTEN>0.0.0.0</LISTEN><PORT></PORT><TYPE>VNC</TYPE><RANDOM_PASSWD></RANDOM_PASSWD></GRAPHICS><DISK><DRIVER></DRIVER><IMAGE>ubuntu_14.04</IMAGE><IMAGE_UNAME>oneadmin</IMAGE_UNAME></DISK><FROM_APP></FROM_APP><FROM_APP_NAME></FROM_APP_NAME><NIC><NETWORK>open-vs</NETWORK><NETWORK_UNAME>oneadmin</NETWORK_UNAME></NIC><OS><ARCH>x86_64</ARCH></OS></Template>]\n" 
time="2016-03-09T16:25:50+05:30" level=debug msg="\x1b[1;34;10m  > [one-go] ( ´ ▽ ` ) SUCCESS\x1b[0m"

**Comment by thomasalrin** [comment]
For HDD, you can add the 'size' key in 'disk'
DISK=[IMAGE="ubuntu_14.04",IMAGE_UNAME="oneadmin",SIZE="20480"]

**Comment by indykish** [comment]
HDD and Memory in MB., IMAGE is already set.
