### ISSUE TITLE
Panic when step 3:deduct-cons-machine action 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/vertice#224]
UPDATE vertice.assembly SET Inputs = ?, Status = ? WHERE id = ? AND org_id = ? [[{"key":"domain","value":"megambox.com"} {"key":"sshkey","value":"vs"} {"key":"provider","value":"one"} {"key":"cpu","value":"1 Core"} {"key":"ram","value":"1 GB"} {"key":"hdd","value":"24 GB SSD"} {"key":"version","value":"14.04"} {"key":"lastsuccessstatusupdate","value":"11 Mar 16 10:49 EST"} {"key":"status","value":"launched"}] launched ASM8847000949932033293 ORG8507512329171442815]
time="2016-03-11T10:49:41-05:00" level=debug msg="\x1b[1;32;10m  => step 3: deduct-cons-machine action\x1b[0m" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5c65e4]

goroutine 333 [running]:
panic(0xc98de0, 0xc820010070)
	/home/ranjitha/software/go/src/runtime/panic.go:464 +0x3e6
github.com/megamsys/vertice/events.(*EventsWriter).Write(0x0, 0xc8204132c0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/events/writer.go:55 +0x24
github.com/megamsys/vertice/events.(*MultiEvent).Write(0xc820445138, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/events/info.go:133 +0x11a
github.com/megamsys/vertice/provision/one/machine.(*Machine).Deduct(0xc820451290, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/machine/machine.go:96 +0x2b8
github.com/megamsys/vertice/provision/one.glob.func5(0xd444c0, 0xc820451200, 0xc820406350, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/actions.go:130 +0x392
github.com/megamsys/libgo/action.(*Pipeline).Execute(0xc8203df5c0, 0xc820406350, 0x1, 0x1, 0x0, 0x0)
	/home/ranjitha/.go/src/github.com/megamsys/libgo/action/action.go:147 +0xc3d
github.com/megamsys/vertice/provision/one.(*oneProvisioner).deployPipeline(0xc820121cb0, 0xc8203f42c0, 0xc820406300, 0xc, 0x7fa9864d10f0, 0xc8203df4e0, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/provisioner.go:169 +0x3f0
github.com/megamsys/vertice/provision/one.(*oneProvisioner).ImageDeploy(0xc820121cb0, 0xc8203f42c0, 0xc820406300, 0xc, 0x7fa9864d10f0, 0xc8203df4e0, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/provisioner.go:140 +0x36d
github.com/megamsys/vertice/carton.deployToProvisioner(0xc820020258, 0x7fa9864d10f0, 0xc8203df4e0, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/deploy.go:74 +0x202
github.com/megamsys/vertice/carton.Deploy(0xc820020258, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/deploy.go:59 +0x2c1
github.com/megamsys/vertice/carton.(*Carton).Deploy(0xc8203bf320, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/carton.go:75 +0x11d
github.com/megamsys/vertice/carton.CreateProcess.Process(0xc8201d2e00, 0x16, 0xc820020208, 0x1, 0x1, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/megd_process.go:37 +0x74
github.com/megamsys/vertice/carton.(*CreateProcess).Process(0xc8202eed80, 0xc820020208, 0x1, 0x1, 0x0, 0x0)
	<autogenerated>:3 +0xc2
github.com/megamsys/vertice/carton.(*ReqOperator).Accept(0xc820445f38, 0xc820445f08, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/req_operator.go:41 +0x1a7
github.com/megamsys/vertice/subd/deployd.(*Handler).serveNSQ(0xc820157060, 0xc82018ef60, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/subd/deployd/handler.go:24 +0x150
created by github.com/megamsys/vertice/subd/deployd.(*Service).processNSQ
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/subd/deployd/service.go:74 +0xc8

**Comment by indykish** [comment]
This is due to eventswriter null. Its fixed.
