### ISSUE TITLE
when launch torpedo the vertice restart

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/vertice#227]
![vertice](https://cloud.githubusercontent.com/assets/13765880/13776578/ee2eaed2-ead0-11e5-8d51-9f64526704fd.png)

**Comment by ranjithamca** [comment]
-- ks &gocassa.k{qe:gocassa.goCQLBackend{session:(*gocql.Session)(0xc820532000)}, name:"vertice", debugMode:false, tableFactory:(*gocassa.k)(0xc82035a3c0)}time="2016-03-15T17:08:24+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] fetch\x1b[0m (assembly, %!s(MISSING))" 
time="2016-03-15T17:08:24+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] table assembly\x1b[0m" 
time="2016-03-15T17:08:24+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] read\x1b[0m" 
SELECT status, created_at, components, id, json_claz, tosca_type, policies, org_id, name, inputs, outputs FROM vertice.assembly  WHERE id = ? ALLOW FILTERING [ASM5762234437021189855]
time="2016-03-15T17:08:24+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] keyspace vertice\x1b[0m" 
-- ks &gocassa.k{qe:gocassa.goCQLBackend{session:(*gocql.Session)(0xc820308900)}, name:"vertice", debugMode:false, tableFactory:(*gocassa.k)(0xc82035b140)}time="2016-03-15T17:08:24+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] fetch\x1b[0m (assembly, %!s(MISSING))" 
time="2016-03-15T17:08:24+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] table assembly\x1b[0m" 
time="2016-03-15T17:08:24+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] update\x1b[0m" 
UPDATE vertice.assembly SET Inputs = ?, Status = ? WHERE id = ? AND org_id = ? [[{"key":"domain","value":"megambox.com"} {"key":"sshkey","value":"rr"} {"key":"provider","value":"one"} {"key":"cpu","value":"1 Core"} {"key":"ram","value":"1 GB"} {"key":"hdd","value":"24 GB SSD"} {"key":"version","value":"14.04"} {"key":"lastsuccessstatusupdate","value":"15 Mar 16 17:08 IST"} {"key":"status","value":"launched"}] launched ASM5762234437021189855 ORG5817190780766689580]
time="2016-03-15T17:08:24+05:30" level=debug msg="\x1b[1;32;10m  => step 3: deduct-cons-machine action\x1b[0m" 
time="2016-03-15T17:08:24+05:30" level=debug msg="predominance.megambox.com_log:{15 Mar 16 17:08 IST   update status for machine (predominance.megambox.com, launching) OK megd predominance ASM5762234437021189855}" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5c65e4]

goroutine 1029 [running]:
panic(0xc98de0, 0xc820014070)
	/home/ranjitha/software/go/src/runtime/panic.go:464 +0x3e6
github.com/megamsys/vertice/events.(*EventsWriter).Write(0x0, 0xc8203584b0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/events/writer.go:55 +0x24
github.com/megamsys/vertice/events.(*MultiEvent).Write(0xc8205ad138, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/events/info.go:133 +0x11a
github.com/megamsys/vertice/provision/one/machine.(*Machine).Deduct(0xc820494c60, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/machine/machine.go:96 +0x2b8
github.com/megamsys/vertice/provision/one.glob.func5(0xd444c0, 0xc820494bd0, 0xc8205c0e50, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/actions.go:130 +0x392
github.com/megamsys/libgo/action.(*Pipeline).Execute(0xc820269c00, 0xc8205c0e50, 0x1, 0x1, 0x0, 0x0)
	/home/ranjitha/.go/src/github.com/megamsys/libgo/action/action.go:147 +0xc3d
github.com/megamsys/vertice/provision/one.(*oneProvisioner).deployPipeline(0xc82012fd70, 0xc8205a4580, 0xc8205c0e00, 0xc, 0x7fd2baba35a0, 0xc820269b20, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/provisioner.go:169 +0x3f0
github.com/megamsys/vertice/provision/one.(*oneProvisioner).ImageDeploy(0xc82012fd70, 0xc8205a4580, 0xc8205c0e00, 0xc, 0x7fd2baba35a0, 0xc820269b20, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/provision/one/provisioner.go:140 +0x36d
github.com/megamsys/vertice/carton.deployToProvisioner(0xc8204680f0, 0x7fd2baba35a0, 0xc820269b20, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/deploy.go:74 +0x202
github.com/megamsys/vertice/carton.Deploy(0xc8204680f0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/deploy.go:59 +0x2c1
github.com/megamsys/vertice/carton.(*Carton).Deploy(0xc82054c900, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/carton.go:75 +0x11d
github.com/megamsys/vertice/carton.CreateProcess.Process(0xc82049ece0, 0x16, 0xc820490190, 0x1, 0x1, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/megd_process.go:37 +0x74
github.com/megamsys/vertice/carton.(*CreateProcess).Process(0xc820386f20, 0xc820490190, 0x1, 0x1, 0x0, 0x0)
	<autogenerated>:3 +0xc2
github.com/megamsys/vertice/carton.(*ReqOperator).Accept(0xc8205adf38, 0xc8205adf08, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/carton/req_operator.go:41 +0x1a7
github.com/megamsys/vertice/subd/deployd.(*Handler).serveNSQ(0xc8201a0fd0, 0xc8202661e0, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/subd/deployd/handler.go:24 +0x150
created by github.com/megamsys/vertice/subd/deployd.(*Service).processNSQ
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/subd/deployd/service.go:74 +0xc8
[2016-03-15T11:38:25.006Z] (sys) vertice starting
time="2016-03-15T17:08:25+05:30" level=info msg=vertice. 
time="2016-03-15T17:08:25+05:30" level=warning msg="Using configuration at: /var/lib/megam/vertice/vertice.conf" 
time="2016-03-15T17:08:25+05:30" level=debug msg="\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;36;10mMeta\x1b[0m\nHome      \t/var/lib/megam\nDir       \t/var/lib/megam/vertice\nApi       \thttps://api.megam.io/v2\nNSQd      \t103.56.92.4:4150\nScylla    \t192.168.1.100\nScyllaKeyspace\tvertice\n---\x1b[1;37;10m\nConfig:\x1b[0m\t\x1b[0;36;10mDeployd\x1b[0m\nprovider\tone\nendpoint\thttp://192.168.1.105:2633/RPC2\nuserid    \toneadmin\ntemplate\tmegam\nimage    \tmegam\npassword\tyourWuOtHij3\n---\n\x1b[1;37;10m\nConfig:\x1b[0m\t\x1b[0;36;10mhttpd\x1b[0m\nenabled     \ttrue\nbind_address\t192.168.1.105:7777\nusetls      \tfalse\n---\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;36;10mdocker\x1b[0m\nenabled      \ttrue\nregistry\thttps://hub.docker.com\nswarm    \ttcp://103.56.92.52:2375\nmem       \t268435456\nswap    \t220200960\ncpuperiod    \t25s\ncpuquota    \t25s\n---\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;32;10mbridges\x1b[0m\n\n\x1b[0;37;10mBridge\x1b[0m\t\x1b[0;34;10mmegdock_pub\x1b[0m\nnetwork\t103.56.93.1/24\ngateway\t103.56.92.1\n---\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;36;10mMetricsd\x1b[0m\nenabled\tfalse\ncollect_interval\t10m0s\n---\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;36;10mRoute\x1b[0m\nenabled  \ttrue\naccess_key\tabcd\nsecret_key\tefgh\n---\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;36;10mEventsd\x1b[0m\nenabled      \tfalse\n\x1b[0;32;10mMailgun\x1b[0m\napi_key\ttemp\ndomain\tojamail.megambox.com\nnilavu    \thttps://console.megam.io\nlogo      \thttps://s3-ap-southeast-1.amazonaws.com/megampub/images/mailers/megam_vertice.png\x1b[0;32;10m\nInfobip\x1b[0m\nusername\tinfo_username\npassword\tinfo_pw\napi_key\tinfo_apiky\napplication_id\tinfo_apiid\nmessage_id\tinfo_msgid\x1b[0;32;10m\nSlack\x1b[0m\ntoken\ttemp\nchannel\tahoy\n\x1b[0;32;10m\nBillmgr\x1b[0m\npiggybanks    \tscylladb,whmcs\nwhmcs_username\t\nwhmcs_password\t\nwhmcs_key     \tdummykey\nwhmcs_domain  \thttp://localhost.com/billing\n---" 

,--.               ██╗   ██╗███████╗██████╗ ████████╗██╗ ██████╗███████╗
\  _\_             ██║   ██║██╔════╝██╔══██╗╚══██╔══╝██║██╔════╝██╔════╝
_\/_|_\____.'\     ██║   ██║█████╗  ██████╔╝   ██║   ██║██║     █████╗
-(___.--._____(    ╚██╗ ██╔╝██╔══╝  ██╔══██╗   ██║   ██║██║     ██╔══╝
   \   \            ╚████╔╝ ███████╗██║  ██║   ██║   ██║╚██████╗███████╗
    \   \            ╚═══╝  ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝ ╚═════╝╚══════╝
     '--'
starting ⠏        1.0
time="2016-03-15T17:08:25+05:30" level=warning msg="skip metricsd service." 
time="2016-03-15T17:08:25+05:30" level=warning msg="skip eventsd service." 
time="2016-03-15T17:08:25+05:30" level=info msg="writing CPU profile to: cpuprof" 
time="2016-03-15T17:08:25+05:30" level=info msg="writing mem profile to: memprof" 
time="2016-03-15T17:08:25+05:30" level=debug msg="\x1b[1;34;10m  > configuring \x1b[0mone " 
time="2016-03-15T17:08:25+05:30" level=debug msg="\x1b[1;34;10m  > one initialized\x1b[0m" 
time="2016-03-15T17:08:25+05:30" level=info msg="\x1b[1;37;10m  > one \x1b[0m\t\x1b[0;36;10mready\x1b[0m" 
time="2016-03-15T17:08:25+05:30" level=info msg="starting httpd service" 
time="2016-03-15T17:08:25+05:30" level=debug msg="\x1b[1;34;10m  > configuring \x1b[0mdocker " 
time="2016-03-15T17:08:25+05:30" level=debug msg="\x1b[1;34;10m  > docker initialized\x1b[0m" 
time="2016-03-15T17:08:25+05:30" level=info msg="\x1b[1;37;10m  > docker \x1b[0m\t\x1b[0;36;10mready\x1b[0m" 
time="2016-03-15T17:08:25+05:30" level=debug msg="\x1b[1;32;10mō͡≡o˞̶  engine up\x1b[0m" 
time="2016-03-15T17:08:25+05:30" level=info msg="starting deployd service" 
time="2016-03-15T17:08:25+05:30" level=info msg="  > httpd http://192.168.1.105:7777" 
time="2016-03-15T17:08:25+05:30" level=info msg="starting dockerd service" 
2016/03/15 17:08:25 Handler: topic=vms channel=engine
2016/03/15 17:08:25 Handler: topic=containers channel=engine
time="2016-03-15T17:08:25+05:30" level=debug msg="minibuses.megambox.com_log: start" 
2016/03/15 17:08:25 Handler: topic=minibuses.megambox.com_log channel=clients
panic: concurrent write to websocket connection

goroutine 708 [running]:
panic(0xb1b0c0, 0xc8201b1a80)
	/home/ranjitha/software/go/src/runtime/panic.go:464 +0x3e6
github.com/gorilla/websocket.(*Conn).flushFrame(0xc8201b2f00, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/.go/src/github.com/gorilla/websocket/conn.go:450 +0x5ba
github.com/gorilla/websocket.(*Conn).NextWriter(0xc8201b2f00, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/ranjitha/.go/src/github.com/gorilla/websocket/conn.go:378 +0x9b
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc8201b2f00, 0x1, 0xc82018f450, 0xb8, 0xc5, 0x0, 0x0)
	/home/ranjitha/.go/src/github.com/gorilla/websocket/conn.go:585 +0x4f
created by github.com/megamsys/vertice/api.logs
	/home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/api/box.go:50 +0x333
[2016-03-15T11:38:32.856Z] (sys) vertice starting
time="2016-03-15T17:08:32+05:30" level=info msg=vertice. 
time="2016-03-15T17:08:32+05:30" level=warning msg="Using configuration at: /var/lib/megam/vertice/vertice.conf" 
time="2016-03-15T17:08:32+05:30" level=debug msg="\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;36;10mMeta\x1b[0m\nHome      \t/var/lib/megam\nDir       \t/var/lib/megam/vertice\nApi       \thttps://api.megam.io/v2\nNSQd      \t103.56.92.4:4150\nScylla    \t192.168.1.100\nScyllaKeyspace\tvertice\n---\x1b[1;37;10m\nConfig:\x1b[0m\t\x1b[0;36;10mDeployd\x1b[0m\nprovider\tone\nendpoint\thttp://192.168.1.105:2633/RPC2\nuserid    \toneadmin\ntemplate\tmegam\nimage    \tmegam\npassword\tyourWuOtHij3\n---\n\x1b[1;37;10m\nConfig:\x1b[0m\t\x1b[0;36;10mhttpd\x1b[0m\nenabled     \ttrue\nbind_address\t192.168.1.105:7777\nusetls      \tfalse\n---\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;36;10mdocker\x1b[0m\nenabled      \ttrue\nregistry\thttps://hub.docker.com\nswarm    \ttcp://103.56.92.52:2375\nmem       \t268435456\nswap    \t220200960\ncpuperiod    \t25s\ncpuquota    \t25s\n---\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;32;10mbridges\x1b[0m\n\n\x1b[0;37;10mBridge\x1b[0m\t\x1b[0;34;10mmegdock_pub\x1b[0m\nnetwork\t103.56.93.1/24\ngateway\t103.56.92.1\n---\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;36;10mMetricsd\x1b[0m\nenabled\tfalse\ncollect_interval\t10m0s\n---\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;36;10mRoute\x1b[0m\nenabled  \ttrue\naccess_key\tabcd\nsecret_key\tefgh\n---\n\x1b[1;37;10mConfig:\x1b[0m\t\x1b[0;36;10mEventsd\x1b[0m\nenabled      \tfalse\n\x1b[0;32;10mMailgun\x1b[0m\napi_key\ttemp\ndomain\tojamail.megambox.com\nnilavu    \thttps://console.megam.io\nlogo      \thttps://s3-ap-southeast-1.amazonaws.com/megampub/images/mailers/megam_vertice.png\x1b[0;32;10m\nInfobip\x1b[0m\nusername\tinfo_username\npassword\tinfo_pw\napi_key\tinfo_apiky\napplication_id\tinfo_apiid\nmessage_id\tinfo_msgid\x1b[0;32;10m\nSlack\x1b[0m\ntoken\ttemp\nchannel\tahoy\n\x1b[0;32;10m\nBillmgr\x1b[0m\npiggybanks    \tscylladb,whmcs\nwhmcs_username\t\nwhmcs_password\t\nwhmcs_key     \tdummykey\nwhmcs_domain  \thttp://localhost.com/billing\n---" 

,--.               ██╗   ██╗███████╗██████╗ ████████╗██╗ ██████╗███████╗
\  _\_             ██║   ██║██╔════╝██╔══██╗╚══██╔══╝██║██╔════╝██╔════╝
_\/_|_\____.'\     ██║   ██║█████╗  ██████╔╝   ██║   ██║██║     █████╗
-(___.--._____(    ╚██╗ ██╔╝██╔══╝  ██╔══██╗   ██║   ██║██║     ██╔══╝
   \   \            ╚████╔╝ ███████╗██║  ██║   ██║   ██║╚██████╗███████╗
    \   \            ╚═══╝  ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝ ╚═════╝╚══════╝
     '--'
starting ⠏        1.0
time="2016-03-15T17:08:32+05:30" level=warning msg="skip metricsd service." 
time="2016-03-15T17:08:32+05:30" level=warning msg="skip eventsd service." 
time="2016-03-15T17:08:32+05:30" level=info msg="writing CPU profile to: cpuprof" 
time="2016-03-15T17:08:32+05:30" level=info msg="writing mem profile to: memprof" 
time="2016-03-15T17:08:32+05:30" level=debug msg="\x1b[1;34;10m  > configuring \x1b[0mone " 
time="2016-03-15T17:08:32+05:30" level=debug msg="\x1b[1;34;10m  > one initialized\x1b[0m" 
time="2016-03-15T17:08:32+05:30" level=info msg="\x1b[1;37;10m  > one \x1b[0m\t\x1b[0;36;10mready\x1b[0m" 
time="2016-03-15T17:08:32+05:30" level=info msg="starting httpd service" 
time="2016-03-15T17:08:32+05:30" level=debug msg="\x1b[1;34;10m  > configuring \x1b[0mdocker " 
time="2016-03-15T17:08:32+05:30" level=debug msg="\x1b[1;34;10m  > docker initialized\x1b[0m" 
time="2016-03-15T17:08:32+05:30" level=info msg="\x1b[1;37;10m  > docker \x1b[0m\t\x1b[0;36;10mready\x1b[0m" 
time="2016-03-15T17:08:32+05:30" level=debug msg="\x1b[1;32;10mō͡≡o˞̶  engine up\x1b[0m" 
time="2016-03-15T17:08:32+05:30" level=info msg="starting deployd service" 
time="2016-03-15T17:08:32+05:30" level=info msg="starting dockerd service" 
time="2016-03-15T17:08:32+05:30" level=info msg="  > httpd http://192.168.1.105:7777" 
2016/03/15 17:08:32 Handler: topic=vms channel=engine
2016/03/15 17:08:32 Handler: topic=containers channel=engine
time="2016-03-15T17:08:32+05:30" level=debug msg="minibuses.megambox.com_log: start" 
2016/03/15 17:08:32 Handler: topic=minibuses.megambox.com_log channel=clients

**Comment by indykish** [comment]
2 bugs

1. When events is false, it crashes. Its fixed.

```go
goroutine 1029 [running]:
panic(0xc98de0, 0xc820014070)
/home/ranjitha/software/go/src/runtime/panic.go:464 +0x3e6
github.com/megamsys/vertice/events.(EventsWriter).Write(0x0, 0xc8203584b0, 0x0, 0x0)
```

2. Concurrent websocket write happen by spanning multiple channel for each write. 
  
```go
home/ranjitha/code/megam/workspace/packager/vertice/build/trusty/vertice/src/github.com/megamsys/vertice/api/box.go:50 +0x333
```
Fix: I am moving to serial mode.
