### ISSUE TITLE
when we enable the billing this error will occured

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#233]
time="2016-05-10T10:48:07+03:00" level=info msg="WRIT user onboard" 
time="2016-05-10T10:48:07+03:00" level=info msg="Event:BILL:onboard" 
time="2016-05-10T10:48:07+03:00" level=debug msg="User Onboarding..." 
time="2016-05-10T10:48:07+03:00" level=debug msg="\x1b[1;34;10m  > [scylla] keyspace vertice\x1b[0m" 
-- ks &gocassa.k{qe:gocassa.goCQLBackend{session:(*gocql.Session)(0xc820426480)}, name:"vertice", debugMode:false, tableFactory:(*gocassa.k)(0xc8203cabc0)}time="2016-05-10T10:48:07+03:00" level=debug msg="\x1b[1;34;10m  > [scylla] fetch\x1b[0m (accounts, %!s(MISSING))" 
time="2016-05-10T10:48:07+03:00" level=debug msg="\x1b[1;34;10m  > [scylla] table accounts\x1b[0m" 
time="2016-05-10T10:48:07+03:00" level=debug msg="\x1b[1;34;10m  > [scylla] read\x1b[0m" 
SELECT phone, password, password_reset_key, authority, password_reset_sent_at, status, id, first_name, last_name, email, api_key FROM vertice.accounts  WHERE email = ? ALLOW FILTERING [rajram.rajesh21@gmail.com]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7841f7]

goroutine 19 [running]:
panic(0xcb2600, 0xc820014070)
	/home/ranjitha/software/go/src/runtime/panic.go:481 +0x3e6
github.com/megamsys/libgo/events/bills.whmcsBiller.Onboard(0x7fd2428f2900, 0x0, 0x0, 0x0, 0x0, 0xc820430080, 0xc8201cb0e0, 0x0, 0x0)
	/home/ranjitha/.go/src/github.com/megamsys/libgo/events/bills/whmcs.go:76 +0x677
github.com/megamsys/libgo/events/bills.(*whmcsBiller).Onboard(0xc820131800, 0xc820430080, 0xc8201cb0e0, 0x0, 0x0)
	<autogenerated>:18 +0xb8
github.com/megamsys/libgo/events.(*Bill).OnboardFunc(0xc8201b7840, 0xc82024e2a0, 0x0, 0x0)
	/home/ranjitha/.go/src/github.com/megamsys/libgo/events/bill.go:73 +0x21c
github.com/megamsys/libgo/events.(*Bill).OnboardFunc-fm(0xc82024e2a0, 0x0, 0x0)
	/home/ranjitha/.go/src/github.com/megamsys/libgo/events/writer.go:99 +0x38
github.com/megamsys/libgo/events.(*User).after(0xc8201b3970, 0xc82024e2a0, 0x0, 0x0)
	/home/ranjitha/.go/src/github.com/megamsys/libgo/events/user.go:88 +0xd1
github.com/megamsys/libgo/events.(*User).alert(0xc8201b3970, 0xc82024e2a0, 0x0, 0x0)
	/home/ranjitha/.go/src/github.com/megamsys/libgo/events/user.go:81 +0x163
github.com/megamsys/libgo/events.(*User).Watch.func1(0xc8201b39f0, 0xc8201b3970)
	/home/ranjitha/.go/src/github.com/megamsys/libgo/events/user.go:60 +0xd8
created by github.com/megamsys/libgo/events.(*User).Watch

**Comment by indykish** [comment]
@Rajesh-Rajagopal  It trying to create an id in WHMCS, is billing enabled ?

**Comment by vijaykanthm28** [comment]
for RC we have to fix

**Comment by vijaykanthm28** [comment]
@rajesh-rajagopal  test and close it on new build
