### ISSUE TITLE
Support for region, Storage type, Private network, and IPV6

### ISSUE THREAD

**Issue by indykish** [megamsys/vertice#245]
Our 1.5 UI has the following options as seen in Here is the launch step video . https://youtu.be/4VxclxLkbt8
The new  `inputs` has 

1.Ability to launch in a region  '{"key":"region","value":"sydney"}',
2.Ability to attach private network `'{"key":"ipv4private","value":"true"}`
3.Ability to attach public  ipv6 network `'{"key":"ipv6public","value":"true"}`
4.Ability to attach private ipv6 network `"key":"ipv6private","value":"false"}`
4.Ability to launch in HDD or SSD storage `'{"key":"storagetype","value":"HDD"}`

**Comment by vijaykanthm28** [comment]
we have fix in RC

**Comment by vijaykanthm28** [comment]
@indykish 
we can deploy VMs based on storage (HDD/SSD)
but can not for containers
