### ISSUE TITLE
Events is disabled it shows panic error

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#250]
time="2016-09-13T20:09:18+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] Connection close\x1b[0m"
Sep 13 20:09:18 megamswasa vertice[57376]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 13 20:09:18 megamswasa vertice[57376]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b4e92]
Sep 13 20:09:18 megamswasa vertice[57376]: goroutine 359 [running]:
Sep 13 20:09:18 megamswasa vertice[57376]: panic(0xaa89c0, 0xc42000e050)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/software/go/src/runtime/panic.go:500 +0x1a1
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/libgo/events.(*EventsWriter).Write(0x0, 0xc4204bc540, 0x1, 0x1)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/libgo/events/writer.go:56 +0x22
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/libgo/events.(*MultiEvent).Write(0xc420180ae0, 0xc4204bc540, 0x10a8ce0)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/libgo/events/info.go:126 +0xd1
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/carton.(*Ambly).trigger_event(0xc4203b1680, 0xb7d05e, 0x9, 0x1, 0x1)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/assembly.go:261 +0x5c1
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/carton.(*Ambly).SetStatus(0xc4203b1680, 0xb7d05e, 0x9, 0x0, 0x0)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/assembly.go:214 +0x7e7
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/provision/one/machine.(*Machine).SetStatus(0xc420181330, 0xb7d05e, 0x9, 0x7e, 0x0)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/provision/one/machine/machine.go:227 +0x1c4
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/provision/one.glob..func1(0x0, 0x0, 0xc42044c8a0, 0x1, 0x1, 0x0, 0xb77bda, 0x4, 0xc4202f7680)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/provision/one/actions.go:79 +0x390
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/libgo/action.(*Pipeline).Execute(0xc420436ca0, 0xc42044c8a0, 0x1, 0x1, 0xc4203adb00, 0x0)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/libgo/action/action.go:147 +0x7de
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/provision/one.(*oneProvisioner).deployPipeline(0xc420187040, 0xc4203c2d00, 0xc42044c7b0, 0xc, 0x1089a60, 0xc420436be0, 0x0, 0x7b, 0x0, 0x0)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/provision/one/provisioner.go:253 +0x3de
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/provision/one.(*oneProvisioner).ImageDeploy(0xc420187040, 0xc4203c2d00, 0xc42044c7b0, 0xc, 0x1089a60, 0xc420436be0, 0x2, 0x2, 0xc420181b90, 0x2)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/provision/one/provisioner.go:216 +0x285
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/carton.deployToProvisioner(0xc42036e0b0, 0x1089a60, 0xc420436be0, 0x1089a60, 0xc420436be0, 0xc41ffe1e97, 0xc420181bb0)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/deploy.go:73 +0x2bc
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/carton.Deploy(0xc42036e0b0, 0x0, 0x0)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/deploy.go:58 +0x229
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/carton.(*Carton).Deploy(0xc4204203c0, 0x32, 0x0)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/carton.go:82 +0x114
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/carton.CreateProcess.Process(0xc42039ca60, 0x16, 0xc42036e078, 0x1, 0x1, 0x0, 0x0)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/megd_process.go:37 +0x48
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/carton.(*CreateProcess).Process(0xc42035a8c0, 0xc42036e078, 0x1, 0x1, 0x0, 0x0)
Sep 13 20:09:18 megamswasa vertice[57376]:         <autogenerated>:3 +0x79
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/carton.(*ReqOperator).Accept(0xc420181f30, 0xc420181f20, 0xc42037ea90, 0x5)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/req_operator.go:42 +0x166
Sep 13 20:09:18 megamswasa vertice[57376]: github.com/megamsys/vertice/subd/deployd.(*Handler).serveNSQ(0xc4201bf6d0, 0xc4203820c0, 0x0, 0x0)
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/subd/deployd/handler.go:23 +0x101
Sep 13 20:09:18 megamswasa vertice[57376]: created by github.com/megamsys/vertice/subd/deployd.(*Service).processNSQ
Sep 13 20:09:18 megamswasa vertice[57376]:         /home/alrin/code/megam/workspace/go/src/github.com/megamsys/vertice/subd/deployd/service.go:77 +0x9a
Sep 13 20:09:18 megamswasa systemd[1]: vertice.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 13 20:09:18 megamswasa systemd[1]: vertice.service: Unit entered failed state.
Sep 13 20:09:18 megamswasa systemd[1]: vertice.service: Failed with result 'exit-code'.

**Comment by vijaykanthm28** [comment]
we have to fix for RC

**Comment by vijaykanthm28** [comment]
@rajesh-rajagopal  test and close it on new build

**Comment by indykish** [comment]
@vijaykanthm28  Appreciate your effort in taking ownership and closing vertice/gulp fixes. Thanks for ensuring that work gets closed in your vacation. Keep it up.

**Comment by rajesh-rajagopal** [comment]
@vijaykanthm28 This issue has been fixed. now its doesn't show the panic error

**Comment by indykish** [comment]
@rajesh-rajagopal  Thanks. lets close it.

**Comment by rajesh-rajagopal** [comment]
@indykish  ok sir
