### ISSUE TITLE
enabling billing in vertice.conf file this error occured

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#253]
UPDATE vertice.events_for_vms SET data = ? WHERE event_type = ? AND created_at = ? AND assembly_id = ? AND account_id = ? [[{"key":"status","value":"launched"} {"key":"description","value":"Machine inaugurals was initialized on cloud.."}] compute.instance.launched 2016-07-06 14:28:41.050436852 +0000 UTC ASM6365647831203335142 rajeshr@megam.io]
time="2016-07-06T14:28:41Z" level=debug msg="\x1b[1;34;10m  > [scylla] keyspace vertice\x1b[0m" 
-- ks &gocassa.k{qe:gocassa.goCQLBackend{session:(*gocql.Session)(0xc820110480)}, name:"vertice", debugMode:false, tableFactory:(*gocassa.k)(0xc8201846c0)}time="2016-07-06T14:28:41Z" level=debug msg="\x1b[1;34;10m  > [scylla] fetch\x1b[0m (balances, %!s(MISSING))" 
time="2016-07-06T14:28:41Z" level=debug msg="\x1b[1;34;10m  > [scylla] table balances\x1b[0m" 
time="2016-07-06T14:28:41Z" level=debug msg="\x1b[1;34;10m  > [scylla] read\x1b[0m" 
SELECT updated_at, id, account_id, credit, created_at FROM vertice.balances ALLOW FILTERING []
time="2016-07-06T14:28:41Z" level=warning msg="Failed to process watch event: scylla.go:49: No rows returned" 
time="2016-07-06T14:28:41Z" level=info msg="Event:BILL:transaction"

**Comment by vijaykanthm28** [comment]
we have to fix for RC

**Comment by vijaykanthm28** [comment]
@rajesh-rajagopal  test and close it on new build
