### ISSUE TITLE
Panic in vertice, opennebula ip's are finished

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#264]
time="2016-07-29T05:21:56Z" level=debug msg="nuke and set outputs in scylla [map[vmid:[\"[TemplateInstantiate] Error allocating a new virtual machine template. Cannot get IP/MAC lease from virtual network 0.\"]]]" 
time="2016-07-29T05:21:56Z" level=debug msg="\x1b[1;34;10m  > [scylla] Connection close\x1b[0m" 
YToxOntzOjA6IiI7czozMzoiSWFtQXRsYXN7NzR9Tm9iZHlDYW5TZWRmZWZkZU1FIzA3Ijt9panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x71fbd6]

goroutine 42 [running]:
panic(0xa880c0, 0xc420012050)
	/home/alrin/software/go/src/runtime/panic.go:500 +0x1a1
github.com/megamsys/libgo/events/bills.whmcsBiller.Onboard(0x0, 0x0, 0x0, 0x0, 0x0, 0xc4201b2000, 0xc4201d33b0, 0x5, 0xe6b501)
	/home/alrin/.go/src/github.com/megamsys/libgo/events/bills/whmcs.go:82 +0x7d6
github.com/megamsys/libgo/events/bills.(*whmcsBiller).Onboard(0xc420135920, 0xc4201b2000, 0xc4201d33b0, 0x0, 0x0)
	<autogenerated>:18 +0x82
github.com/megamsys/libgo/events.(*Bill).OnboardFunc(0xc4201cb2e0, 0xc4203ec060, 0x0, 0x68858a)
	/home/alrin/.go/src/github.com/megamsys/libgo/events/bill.go:73 +0x201
github.com/megamsys/libgo/events.(*Bill).OnboardFunc-fm(0xc4203ec060, 0xc4201d34a0, 0x4)
	/home/alrin/.go/src/github.com/megamsys/libgo/events/writer.go:99 +0x34
github.com/megamsys/libgo/events.(*User).after(0xc4201c8df0, 0xc4203ec060, 0xc4203fc240, 0x0)
	/home/alrin/.go/src/github.com/megamsys/libgo/events/user.go:88 +0x87
github.com/megamsys/libgo/events.(*User).alert(0xc4201c8df0, 0xc4203ec060, 0x0, 0x1)
	/home/alrin/.go/src/github.com/megamsys/libgo/events/user.go:81 +0x12a
github.com/megamsys/libgo/events.(*User).Watch.func1(0xc4201c8e70, 0xc4201c8df0)
	/home/alrin/.go/src/github.com/megamsys/libgo/events/user.go:60 +0xe5
created by github.com/megamsys/libgo/events.(*User).Watch
	/home/alrin/.go/src/github.com/megamsys/libgo/events/user.go:69 +0x7a
[2016-07-29T05:21:56.253Z] (sys) vertice starting
time="2016-07-29T05:21:56Z" level=info msg=vertice. 
{cluster-a eth0 network gateway}
{true [{    0s 0s []} {    0s 0s []} {africa tcp://localhost:2375 :6666 https://hub.docker.com 25s 25s [{   } {   } {cluster-a eth0 network gateway}]}]}
time="2016-07-29T05:21:56Z" level=warning msg="Using configuration at: /var/lib/megam/vertice/vertice.conf" 
{10 one 103.56.93.1/24 103.56.92.1}
time="2016-07-29T05:21:56Z" level=debug msg="%!v(PANIC=runtime error: index out of range)"

**Comment by vijaykanthm28** [comment]
fixed in error #266
