### ISSUE TITLE
when launch torpedo the vertice stop

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/vertice#269]
DEBU[0608]   => step 8: deduct-cons-machine action 
panic: interface conversion: interface is *errors.errorString, not machine.Machine

goroutine 1356 [running]:
panic(0xa8cae0, 0xc4204f3a40)
	/home/ranjitha/software/go/src/runtime/panic.go:500 +0x1a1
github.com/megamsys/vertice/provision/one.glob..func11(0xa6fd80, 0xc420162160, 0xc420447710, 0x1, 0x1, 0x0, 0xb4fdc2, 0x4, 0xc4204f3940)
	/home/ranjitha/code/megam/workspace/go/src/github.com/megamsys/vertice/provision/one/actions.go:189 +0xa1
github.com/megamsys/libgo/action.(*Pipeline).Execute(0xc4204184c0, 0xc420447710, 0x1, 0x1, 0xc42036f8b0, 0x0)
	/home/ranjitha/.go/src/github.com/megamsys/libgo/action/action.go:147 +0x7da
github.com/megamsys/vertice/provision/one.(*oneProvisioner).deployPipeline(0xc42015f440, 0xc420001860, 0xc4204476c0, 0xc, 0xe46cc0, 0xc4204183e0, 0x0, 0x76, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/go/src/github.com/megamsys/vertice/provision/one/provisioner.go:249 +0x3d3
github.com/megamsys/vertice/provision/one.(*oneProvisioner).ImageDeploy(0xc42015f440, 0xc420001860, 0xc4204476c0, 0xc, 0xe46cc0, 0xc4204183e0, 0x2, 0x2, 0xc420487b90, 0x2)
	/home/ranjitha/code/megam/workspace/go/src/github.com/megamsys/vertice/provision/one/provisioner.go:214 +0x285
github.com/megamsys/vertice/carton.deployToProvisioner(0xc420374078, 0xe46cc0, 0xc4204183e0, 0xe46cc0, 0xc4204183e0, 0xc41fffff3c, 0xc420487bb0)
	/home/ranjitha/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/deploy.go:73 +0x2bc
github.com/megamsys/vertice/carton.Deploy(0xc420374078, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/deploy.go:58 +0x225
github.com/megamsys/vertice/carton.(*Carton).Deploy(0xc4201c8140, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/carton.go:82 +0x114
github.com/megamsys/vertice/carton.CreateProcess.Process(0xc4205508c0, 0x16, 0xc420218060, 0x1, 0x1, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/megd_process.go:37 +0x48
github.com/megamsys/vertice/carton.(*CreateProcess).Process(0xc42046a060, 0xc420218060, 0x1, 0x1, 0x0, 0x0)
	<autogenerated>:3 +0x79
github.com/megamsys/vertice/carton.(*ReqOperator).Accept(0xc4203b1f20, 0xc4203b1f10, 0xc42047e7a0, 0x5)
	/home/ranjitha/code/megam/workspace/go/src/github.com/megamsys/vertice/carton/req_operator.go:42 +0x166
github.com/megamsys/vertice/subd/deployd.(*Handler).serveNSQ(0xc4201a57f0, 0xc420544120, 0x0, 0x0)
	/home/ranjitha/code/megam/workspace/go/src/github.com/megamsys/vertice/subd/deployd/handler.go:23 +0xfd
created by github.com/megamsys/vertice/subd/deployd.(*Service).processNSQ
	/home/ranjitha/code/megam/workspace/go/src/github.com/megamsys/vertice/subd/deployd/service.go:77 +0x9a
Makefile:87: recipe for target '_verticer' failed

**Comment by vijaykanthm28** [comment]
we need to debug

**Comment by vijaykanthm28** [comment]
issue fixed
