### ISSUE TITLE
when click snapshot the full pipeline action doesn't happen.

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/vertice#285]
Sep 13 16:23:23 megamswasa vertice[9670]: time="2016-09-13T16:23:23+05:30" level=debug msg="list requests RIP7740718154554064955"
Sep 13 16:23:23 megamswasa vertice[9670]: time="2016-09-13T16:23:23+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] keyspace vertice\x1b[0m"
Sep 13 16:23:23 megamswasa vertice[9670]: -- ks &gocassa.k{qe:gocassa.goCQLBackend{session:(*gocql.Session)(0xc420092240)}, name:"vertice", debugMode:false, tableFactory:(*gocassa.k)(0xc420055880)}&carton.Requests{Id:"", Name:"", CatId:"", Action:"", Category:"", CreatedAt:""}time="2016-09-13T16:23:23+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] fetch\x1b[0m (requests)"
Sep 13 16:23:23 megamswasa vertice[9670]: time="2016-09-13T16:23:23+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] table requests\x1b[0m"
Sep 13 16:23:23 megamswasa vertice[9670]: time="2016-09-13T16:23:23+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] read\x1b[0m"
Sep 13 16:23:23 megamswasa vertice[9670]: SELECT id, name, cat_id, action, category, created_at FROM vertice.requests  WHERE id = ? ALLOW FILTERING [RIP7740718154554064955]
Sep 13 16:23:23 megamswasa vertice[9670]: time="2016-09-13T16:23:23+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] Connection close\x1b[0m"
Sep 13 16:23:23 megamswasa vertice[9670]: time="2016-09-13T16:23:23+05:30" level=debug msg="Requests id: RIP7740718154554064955\nname: snapshot\ncatid: \"\"\naction: disksaveas\ncategory: snapshot\ncreatedat: 2016-09-13 10:53:23 +0000\n"
Sep 13 16:23:23 megamswasa vertice[9670]: time="2016-09-13T16:23:23+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] keyspace vertice\x1b[0m"
Sep 13 16:23:23 megamswasa vertice[9670]: -- ks &gocassa.k{qe:gocassa.goCQLBackend{session:(*gocql.Session)(0xc420092480)}, name:"vertice", debugMode:false, tableFactory:(*gocassa.k)(0xc420380380)}&carton.Snaps{Id:"", OrgId:"", AccountId:"", Name:"", AssemblyId:"", JsonClaz:"", CreatedAt:""}time="2016-09-13T16:23:23+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] fetch\x1b[0m (snapshots)"
Sep 13 16:23:23 megamswasa vertice[9670]: time="2016-09-13T16:23:23+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] table snapshots\x1b[0m"
Sep 13 16:23:23 megamswasa vertice[9670]: time="2016-09-13T16:23:23+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] read\x1b[0m"
Sep 13 16:23:23 megamswasa vertice[9670]: SELECT snap_id, org_id, account_id, name, asm_id, json_claz, created_at FROM vertice.snapshots ALLOW FILTERING []
Sep 13 16:23:23 megamswasa vertice[9670]: time="2016-09-13T16:23:23+05:30" level=debug msg="\x1b[1;34;10m  > [scylla] Connection close\x1b[0m"

**Comment by vijaykanthm28** [comment]
issue is on Nilavu 
is doesn't put assemblies record on 
 id                     | action     | cat_id | category | cattype | created_at                | name
------------------------+------------+--------+----------+---------+---------------------------+----------
 RIP7740718154554064955 | disksaveas |        | snapshot | torpedo | 2016-09-13 10:53:23 +0000 | snapshot
