### ISSUE TITLE
delete the app from the UI doesn't work

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#288]
Try to delete the App in UI. it was deleted from UI, and assemblies table but still is present in the assembly table and opennebula.

**Comment by rajesh-rajagopal** [comment]
Assemblies data are deleted from db, and assembly record is still exist
cqlsh:vertice> SELECT * from assemblies WHERE org_id='ORG8571627885143832322' and id='ASM7549281943338329040';

 org_id | id | assemblies | created_at | inputs | json_claz | name
--------+----+------------+------------+--------+-----------+------


cqlsh:vertice> SELECT * FROM assembly where id='ASM7549281943338329040' ALLOW FILTERING ;
 org_id                 | id                     | account_id                | components                 | created_at                | inputs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | json_claz       | name               | outputs                                                                                                                                                            | policies | state   | status     | tosca_type

 ORG8571627885143832322 | ASM7549281943338329040 | rajram.rajesh21@gmail.com | ['COM7107031884742522449'] | 2016-09-14 12:40:32 +0000 | ['{"key":"domain","value":"megambox.com"}', '{"key":"keypairoption","value":"1"}', '{"key":"sshkey","value":"keythree"}', '{"key":"provider","value":"one"}', '{"key":"cpu","value":"2 Cores"}', '{"key":"ram","value":"2 GB"}', '{"key":"hdd","value":"36 GB"}', '{"key":"version","value":""}', '{"key":"region","value":"chennai"}', '{"key":"resource","value":"c1.medium"}', '{"key":"storage_hddtype","value":"HDD"}', '{"key":"ipv4private","value":"true"}', '{"key":"ipv4public","value":"false"}', '{"key":"ipv6private","value":"false"}', '{"key":"ipv6public","value":"false"}', '{"key":"lastsuccessstatusupdate","value":"14 Sep 16 18:37 IST"}', '{"key":"status","value":"destroying"}'] | Megam::Assembly | nameless-star-7142 | ['{"key":"vmid","value":"434"}', '{"key":"vnchost","value":"192.168.0.115"}', '{"key":"vncport","value":"6334"}', '{"key":"privateipv4","value":"192.168.0.142"}'] |     null | running | destroying | vertice.app.java

**Comment by rathishvbr** [comment]
Sep 26 19:08:02 megamswasa verticegateway[7263]: [debug] application - ====> 192.168.0.118:9000/v2/requests/content
Sep 26 19:08:02 megamswasa verticegateway[7263]: [debug] application - HEAD: ArrayBuffer((Accept,application/json), (Accept-Encoding,gzip), (User-Agent,megam-api/1.7.6), (X-Ruby-Version,2.3.1), (X-Ruby-Platform,x86_64-linux), (X-Megam-HMAC,rat2@rat.com:4aaa1cbd4f64fa45d76961a1970d73b3c7c9c0f54b3293f0f8bd4c43d1d571f8), (X-Megam-DATE,2016-09-26 19:08), (X-Megam-ORG,ORG6286883328505634816), (Host,192.168.0.118:9000), (Content-Length,179))
Sep 26 19:08:02 megamswasa verticegateway[7263]: [debug] application - BODY: {"json_claz":"Megam::Request","id":"ASM6706940798203448317","cat_id":"AMS6320719809075835476","name":"stop","cattype":"app","action":"stop","category":"control","created_at":null}
Sep 26 19:08:02 megamswasa verticegateway[7263]: [debug] application - MEMCACHE:            -->[getAs ?rat2@rat.com]
Sep 26 19:08:02 megamswasa verticegateway[7263]: [debug] application - LIV                  -->[rat2@rat.com]
Sep 26 19:08:02 megamswasa verticegateway[7263]: [debug] application - GOOF                 -->[email/api-key  ✓]
Sep 26 19:08:02 megamswasa verticegateway[7263]: [warn] application - Request.created successfully
Sep 26 19:08:02 megamswasa verticegateway[7263]: [debug] application - NSQ:                 -->[http://192.168.0.118:4151]
Sep 26 19:08:02 megamswasa verticegateway[7263]: [debug] application - Request.published successfully -->[{"json_claz":"Megam::Request","id":"ASM6706940798203448317","cat_id":"AMS6320719809075835476","name":"stop","cattype":"app","action":"stop","category":"control","created_at":null}]


Gateway log while stop a application. Both form are same. But for application doesn't work.

**Comment by indykish** [comment]
@rathishvbr  Now i like it :)

**Comment by indykish** [comment]
@vijaykanthm28  Is there a handler for  `"cattype"=>"app", "category"=>"control"` in `gulpd` ?

This problem isn't in vertice. Its in gulpd.

**Comment by vijaykanthm28** [comment]
@indykish there is no handler for "cattype"=>"app" in vertice and gulpd, we have parse operations only from category=>"control" and action=>"start"

**Comment by rajesh-rajagopal** [comment]
App is deleted from UI. Its work good.
