### ISSUE TITLE
status can be changed as state in lifecycle

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/vertice#313]
herry-5498\ncartonsid: AMS6120631765412270499\naccountsid: vvf@gmail.com\norgid: ORG6336350200669808432\ntosca: vertice.torpedo.ubuntu\nimageversion: \"14.04\"\ncompute:\n  cpushare: 2 Cores\n  memory: 1 GB\n  swap: \"\"\n  hdd: 24 GB\nssh:\n  user: megam\n  prefix: io\ndomainname: megambox.com\nprovider: one\npublicip: \"\"\nvmid: \"1264\"\nregion: chennai\nvnets:\n  ipv4private: \"true\"\n  ipv4public: \"false\"\n  ipv6private: \"false\"\n  ipv6public: \"false\"\nboxes:\n- id: ASM6011310371202931086\n  accountsid: vvf@gmail.com\n  cartonsid: AMS6120631765412270499\n  cartonid: ASM6011310371202931086\n  orgid: ORG6336350200669808432\n  cartonname: proud-cherry-5498\n  name: proud-cherry-5498\n  level: 4\n  domainname: megambox.com\n  tosca: vertice.torpedo.ubuntu\n  imageversion: \"14.04\"\n  compute:\n    cpushare: 2 Cores\n    memory: 1 GB\n    swap: \"\"\n    hdd: 24 GB\n  repo: null\n  status: preerror\n  provider: one\n  publicip: \"\"\n  vmid: \"1264\"\n  region: chennai\n  vnets:\n    ipv4private: \"true\"\n    ipv4public: \"false\"\n    ipv6private: \"false\"\n    ipv6public: \"false\"\n  ssh:\n    user: \"\"\n    prefix: \"\"\n  commit: \"\"\n  envs: []\n  address: null\nstatus: preerror\n]"
Oct 14 12:58:56 megamswasa vertice[51949]: time="2016-10-14T12:58:56+05:30" level=debug msg="\x1b[1;36;10mSTART CARTON AMS6120631765412270499\x1b[0m"
Oct 14 12:58:56 megamswasa vertice[51949]: time="2016-10-14T12:58:56+05:30" level=debug msg="  start cycle for box (ASM6011310371202931086, proud-cherry-5498.megambox.com)"
Oct 14 12:58:56 megamswasa vertice[51949]: start (proud-cherry-5498.megambox.com, preerror, 31.927µs) Unsuccessfull because of lifecycle not allowed

**Comment by vijaykanthm28** [comment]
fixed by pull request #312
