### ISSUE TITLE
Bugs on billing can cause problems

### ISSUE THREAD

**Issue by indykish** [megamsys/vertice#325]
@vijaykanthm28   Check it out and respond.

1.  When do we start charging a VM ?

2. Do we charge a VM thats in preerror state ? 

3. Do we charge VMs that are deleted ?

**Comment by indykish** [comment]
@rajthilakmca  Can you verify this area ?

**Comment by vijaykanthm28** [comment]
@indykish 
1. When do we start charging a VM ?
    while launch we charge some amount and  when period metric collection 
2. Do we charge a VM thats in preerror state ?
    No, we charge only for launched VMs 
3. Do we charge VMs that are deleted ?
    No, we charge only active vms for that particular interval time.

**Comment by indykish** [comment]
We need to fix #332  #331 
So close this.
