### ISSUE TITLE
state and status data mismatch in table 

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/vertice#326]
VM fails with wrong selection of Region.
It Shows me  the preerror status in predeploy page.
but in dashboard the VM state is still initializing it didn't changed as preerror. 
While checking the assembly record in database the state and status is different.

 ORG4962640394024406993 | ASM7162277042278547723 |   jj@q.com |       null | 2016-11-22 07:08:02 +0000 | ['{"key":"domain","value":"megambox.com"}', '{"key":"keypairoption","value":"2"}', '{"key":"root_password","value":""}', '{"key":"sshkey","value":"io"}', '{"key":"provider","value":"one"}', '{"key":"cpu","value":"2 Cores"}', '{"key":"ram","value":"2 GB"}', '{"key":"hdd","value":"48 GB"}', '{"key":"version","value":"7.1"}', '{"key":"region","value":"sydney"}', '{"key":"resource","value":"s1.small"}', '{"key":"storage_hddtype","value":"HDD"}', '{"key":"ipv4private","value":"true"}', '{"key":"ipv4public","value":"false"}', '{"key":"ipv6private","value":"false"}', '{"key":"ipv6public","value":"false"}', '{"key":"bitnami_password","value":""}', '{"key":"bitnami_username","value":""}', '{"key":"root_username","value":""}', '{"key":"snapshot","value":""}', '{"key":"snap_name","value":""}', '{"key":"status","value":"preerror"}', '{"key":"lastsuccessstatusupdate","value":"22 Nov 16 12:39 IST"}'] | Megam::Assembly | frosty-field-7592 |    null |     null | **initializing | preerror** | vertice.torpedo.centos

**Comment by vijaykanthm28** [comment]
Its fixed check in next build @rajesh-rajagopal  @vinomca-megam
