### ISSUE TITLE
VM stays in initialized state in Vertice, when its fully running

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/vertice#333]
VM is running state in Opennubula but in nilavu it only shows initialized state

 ORG8785269433089306483 | ASM6567067436739930769 |   gsh@s.co |       null | 2016-12-05 08:25:05 +0000 |     ['{"key":"domain","value":"megambox.com"}', '{"key":"keypairoption","value":"1"}', '{"key":"root_password","value":""}', '{"key":"sshkey","value":"io"}', '{"key":"provider","value":"one"}', '{"key":"cpu","value":"2 Cores"}', '{"key":"ram","value":"1 GB"}', '{"key":"hdd","value":"24 GB"}', '{"key":"version","value":"7.1"}', '{"key":"region","value":"chennai"}', '{"key":"resource","value":"c1.micro"}', '{"key":"storage_hddtype","value":"HDD"}', '{"key":"ipv4private","value":"true"}', '{"key":"ipv4public","value":"false"}', '{"key":"ipv6private","value":"false"}', '{"key":"ipv6public","value":"false"}', '{"key":"bitnami_password","value":""}', '{"key":"bitnami_username","value":""}', '{"key":"root_username","value":""}', '{"key":"snapshot","value":""}', '{"key":"snap_name","value":""}', '{"key":"lastsuccessstatusupdate","value":"05 Dec 16 13:55 IST"}', '{"key":"status","value":"vm_booting"}'] | Megam::Assembly |     small-sound-9046 | ['{"key":"vmid","value":"62"}', '{"key":"vnchost","value":"192.168.0.115"}', '{"key":"vncport","value":"5962"}'] |     null | initialized | vm_booting | vertice.torpedo.centos

**Comment by indykish** [comment]
`gulp` didn't get started.

@vinomca-megam  Please launch a new one and check it to see if this is still exits

**Comment by vijaykanthm28** [comment]
issue fix
