### ISSUE TITLE
Support to bill vms launched using quota based billing

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/vertice#334]
### Check if  quota exists
1. Perform a query to get the `quota` of a user.

**struct Quota**  to manage the quota.

**Waive quota**
Performs a quota waiver if  QC == QO

Where QC = Quota capacity purchased, QO = Quota collected.

```
QuotaWaiver
- Waive
- NotWaived
```

**Deduct quota to be billed**

```
QuotaDeducter 
- Deduct
```

if `NotWaived` then figure out the delta quota to be billed

QC = "2GB ram, 4core, 4disk"

QO = "3GB ram, 4core, 4disk"

extra =QC - QO

In this case `1GB RAM` needs to be billed as ondemand.

**Comment by vijaykanthm28** [comment]
fixed
