### ISSUE TITLE
Cloud snapshots/storage collector

### ISSUE THREAD

**Issue by indykish** [megamsys/vertice#349]
We need collectors for 

### 1. Snapshots LVM
https://github.com/projectatomic/docker-lvm-plugin
https://github.com/drnic/go-lvm-client

List the LVM snapshots using `go-lvm-client` (i don't know how) since LVM snapshots are node specific. Send the metrics.

### 2. Snapshots Ceph
https://github.com/ceph/go-ceph

Connect to the rbd, and list the images (snapshots) for a user. Send the metrics.
The only issue i see is the `rbd connection` needs the default configuration file.

### 3. Cloud storage
https://github.com/QuentinPerez/go-radosgw
The changes needed are create an administrative id and put it in the `vertice.conf` file.

Use the `admin id`, and  the endpoint of the radosgw to periodically collect the metrics via the `GetUsage` call. 

Send it to the biller and our default Sensor.

We need this for a customer :+1:

**Comment by indykish** [comment]
@rajthilakmca  @ranjithamca  @vijaykanthm28  This is closed i think ?

**Comment by vijaykanthm28** [comment]
@indykish  yes this is closed
