### ISSUE TITLE
snapshot image is ready in opennbula but it show "inprogress" message in UI

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#361]
This is atomdeploy.com

![image](https://cloud.githubusercontent.com/assets/18652643/21812735/e7f059e4-d779-11e6-87b3-a089771b31b2.png)

**Comment by indykish** [comment]
Yes I have the same problem  in astimp.ro.

![screenshot from 2017-01-10 21-15-27](https://cloud.githubusercontent.com/assets/1402479/21812778/1bae7bf8-d77a-11e6-804b-2e1a8cc01f74.png)

**Comment by indykish** [comment]
@rajesh-rajagopal  @rathishvbr @ranjithamca  @vijaykanthm28  This is closed i think ?
