### ISSUE TITLE
CUST : quadcloud.com.au issue to launch machines using vOneCloud

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#369]
In `vertice.conf` there is only one common template, based on that template we launch all images.

But for `quadcloud.com.au customer`,  all the images have seperate template as they are imported from vOneCloud (from VMWare into OpenNebula). 

In this case we import VMTemplates from VMWare using the UI for vOneCloud.

Hence we'll have various templates like

```
virtengineubuntu
virtenginecentos_6.8
```
and so on. 

We need ability to launch via **several templates** as the approach of using a  `common template (megam)  + changing images (ubuntu, fedora ..)` will not work.

**Comment by indykish** [comment]
@vijaykanthm28  Shall we close this issue ? 
@rajthilakmca
