### ISSUE TITLE
we not setup docker at a time when launch a container, it show panic error

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#375]
We are not setup docker or rancher , at the time we launch a container, it raised painc error
( in nilavu conf -> configured rancher) 

ssh:\n    user: megam\n    prefix: \"\"\n  commit: \"\"\n  envs: []\n  address: null\nstatus: i
Jan 18 14:22:00 virtengine01 virtengine[8821]: time="2017-01-18T14:22:00Z" level=debug msg="\x1b[1;36;10mCREATE CARTON AMS4817631944273413456\x
Jan 18 14:22:00 virtengine01 virtengine[8821]: time="2017-01-18T14:22:00Z" level=debug msg="\x1b[1;37;10m==> pipeline [1]\x1b[0m"
Jan 18 14:22:00 virtengine01 virtengine[8821]: time="2017-01-18T14:22:00Z" level=debug msg="\x1b[1;32;10m  => step 0: create-container action\x
Jan 18 14:22:00 virtengine01 virtengine[8821]: panic: interface conversion: interface is nil, not container.Container
Jan 18 14:22:00 virtengine01 virtengine[8821]: goroutine 7983 [running]:
Jan 18 14:22:00 virtengine01 virtengine[8821]: panic(0xbc74a0, 0xc420f58740)
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/golang/go/src/runtime/panic.go:500 +0x1a1
Jan 18 14:22:00 virtengine01 virtengine[8821]: github.com/megamsys/vertice/provision/rancher.glob..func1(0x0, 0x0, 0xc420e52c50, 0x1, 0x1, 0x0,
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/.go/src/github.com/megamsys/vertice/provision/rancher/actions.go:136 +0x8
Jan 18 14:22:00 virtengine01 virtengine[8821]: github.com/megamsys/libgo/action.(*Pipeline).Execute(0xc42100d020, 0xc420e52c50, 0x1, 0x1, 0xc42
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/.go/src/github.com/megamsys/libgo/action/action.go:147 +0x7de
Jan 18 14:22:00 virtengine01 virtengine[8821]: github.com/megamsys/vertice/provision/rancher.(*rancherProvisioner).deployPipeline(0xc4201a2de0,
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/.go/src/github.com/megamsys/vertice/provision/rancher/provisioner.go:186 
Jan 18 14:22:00 virtengine01 virtengine[8821]: github.com/megamsys/vertice/provision/rancher.(*rancherProvisioner).GitDeploy(0xc4201a2de0, 0xc4
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/.go/src/github.com/megamsys/vertice/provision/rancher/provisioner.go:148 
Jan 18 14:22:00 virtengine01 virtengine[8821]: github.com/megamsys/vertice/carton.deployToProvisioner(0xc420024030, 0x1261260, 0xc42100d000, 0x
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/deploy.go:84 +0x31b
Jan 18 14:22:00 virtengine01 virtengine[8821]: github.com/megamsys/vertice/carton.Deploy(0xc420024030, 0x0, 0x0)
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/deploy.go:59 +0x229
Jan 18 14:22:00 virtengine01 virtengine[8821]: github.com/megamsys/vertice/carton.(*Carton).Deploy(0xc420cb6a00, 0x32, 0x0)
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/carton.go:98 +0x101
Jan 18 14:22:00 virtengine01 virtengine[8821]: github.com/megamsys/vertice/carton.CreateProcess.Process(0xc4211b0020, 0x16, 0xc420138068, 0x1, 
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/megd_process.go:37 +0x48
Jan 18 14:22:00 virtengine01 virtengine[8821]: github.com/megamsys/vertice/carton.(*CreateProcess).Process(0xc42119a0c0, 0xc420138068, 0x1, 0x1
Jan 18 14:22:00 virtengine01 virtengine[8821]:         <autogenerated>:3 +0x79
Jan 18 14:22:00 virtengine01 virtengine[8821]: github.com/megamsys/vertice/carton.(*ReqOperator).Accept(0xc420aedf10, 0xc420aeded0, 0xc42119a0c
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/req_operator.go:44 +0x143
Jan 18 14:22:00 virtengine01 virtengine[8821]: github.com/megamsys/vertice/subd/deployd.(*Handler).serveNSQ(0xc4201e3290, 0xc420ad8680, 0x0, 0x
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/.go/src/github.com/megamsys/vertice/subd/deployd/handler.go:24 +0x106
Jan 18 14:22:00 virtengine01 virtengine[8821]: created by github.com/megamsys/vertice/subd/deployd.(*Service).processNSQ
Jan 18 14:22:00 virtengine01 virtengine[8821]:         /home/jonathan/.go/src/github.com/megamsys/vertice/subd/deployd/service.go:76 +0xa3
Jan 18 14:22:00 virtengine01 systemd[1]: virtengine.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 18 14:22:00 virtengine01 systemd[1]: virtengine.service: Unit entered failed state.
Jan 18 14:22:00 virtengine01 systemd[1]: virtengine.service: Failed with result 'exit-code'.

**Comment by vijaykanthm28** [comment]
first step action always should be updateStatusInScylla because container struct build on there 

In this build it skiped updateStatusInScylla the action and only have create container action 

virtengine version 1.5  2017-01-12_10:30:51UTC dfe17b2a2d51d6f852b375c2696ae6f893fa0a3e.

its fixed
