### ISSUE TITLE
insufficient fund - VM launched successfully

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#377]
Manually updated the balance "0" in database afterthat i launched VM.
VM is launched and it go for running state.

![image](https://cloud.githubusercontent.com/assets/18652643/22103525/74f2bfec-de61-11e6-9b0c-1312386f41ba.png)

**Comment by vijaykanthm28** [comment]
fixed by https://github.com/megamsys/libgo/pull/119
