### ISSUE TITLE
Error occur in vertice when stop and start the container 

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/vertice#398]
Error log from vertice

Feb 15 15:13:15 flexengine virtengine[18899]: time="2017-02-15T15:13:15Z" level=debug msg="Request [POST] ==> http://213.4.127.109:9000/v2/eventscontainer/content"
Feb 15 15:13:15 flexengine virtengine[18899]: time="2017-02-15T15:13:15Z" level=debug msg="[Body]  ({\"event_type\":\"compute.container.starting\",\"account_id\":\"info@flexvpc.com\",\"assembly_id\":\"ASM7739618001058705258\",\"data\":[{\"key\":\"status\",\"value\":\"containerstarting\"},{\"key\":\"description\",\"value\":\"Starting process initializing on ..\"}]})"
Feb 15 15:13:15 flexengine virtengine[18899]: time="2017-02-15T15:13:15Z" level=debug msg="Request [POST] ==> http://213.4.127.109:9000/v2/components/update"
Feb 15 15:13:15 flexengine virtengine[18899]: time="2017-02-15T15:13:15Z" level=debug msg="[Body]  ({\"id\":\"COM6315347440156559590\",\"name\":\"nameless-star-2387\",\"org_id\":\"ORG5094974748248522843\",\"tosca_type\":\"docker.container.wordpress\",\"inputs\":[{\"key\":\"domain\",\"value\":\"megambox.com\"},{\"key\":\"keypairoption\",\"value\":\"1\"},{\"key\":\"root_password\",\"value\":\"MTIzNDU2Nzg=\"},{\"key\":\"sshkey\",\"value\":\"\"},{\"key\":\"provider\",\"value\":\"docker\"},{\"key\":\"cpu\",\"value\":\"4 Cores\"},{\"key\":\"ram\",\"value\":\"4 GB\"},{\"key\":\"hdd\",\"value\":\"80 GB\"},{\"key\":\"version\",\"value\":\"\"},{\"key\":\"region\",\"value\":\"China\"},{\"key\":\"resource\",\"value\":\"s-03\"},{\"key\":\"storage_hddtype\",\"value\":\"HDD\"},{\"key\":\"ipv4private\",\"value\":\"true\"},{\"key\":\"ipv4public\",\"value\":\"false\"},{\"key\":\"ipv6private\",\"value\":\"false\"},{\"key\":\"ipv6public\",\"value\":\"false\"},{\"key\":\"bitnami_password\",\"value\":\"true\"},{\"key\":\"bitnami_username\",\"value\":\"true\"},{\"key\":\"app_username\",\"value\":\"\"},{\"key\":\"app_password\",\"value\":\"\"},{\"key\":\"root_username\",\"value\":\"root\"},{\"key\":\"backup\",\"value\":\"\"},{\"key\":\"backup_name\",\"value\":\"\"},{\"key\":\"quota_ids\",\"value\":\"\"},{\"key\":\"vm_cpu_cost_per_hour\",\"value\":\"0.005555555555555556\"},{\"key\":\"vm_ram_cost_per_hour\",\"value\":\"0.005555555555555556\"},{\"key\":\"vm_disk_cost_per_hour\",\"value\":\"0.0001388888888888889\"},{\"key\":\"container_cpu_cost_per_hour\",\"value\":\"0.01\"},{\"key\":\"container_memory_cost_per_hour\",\"value\":\"0.02\"},{\"key\":\"lastsuccessstatusupdate\",\"value\":\"15 Feb 17 15:13 UTC\"},{\"key\":\"status\",\"value\":\"containerstarting\"}],\"outputs\":[],\"envs\":[],\"repo\":{\"rtype\":\"source\",\"branch\":\"\",\"source\":\"docker\",\"oneclick\":\"false\",\"url\":\"wordpress\"},\"artifacts\":{\"artifact_type\":\"\",\"content\":\"\",\"requirements\":[]},\"related_components\":[],\"operations\":[],\"status\":\"containerstarting\",\"state\":\"running\",\"created_at\
Feb 15 15:13:15 flexengine virtengine[18899]: ":\"2017-02-15T14:59:42.000\"})"
Feb 15 15:13:15 flexengine systemd[1]: virtengine.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 15 15:13:15 flexengine systemd[1]: Unit virtengine.service entered failed state.
Feb 15 15:13:15 flexengine systemd[1]: virtengine.service failed.
Feb 15 15:13:15 flexengine virtengine[18899]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 15 15:13:15 flexengine virtengine[18899]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa355e0]
Feb 15 15:13:15 flexengine virtengine[18899]: goroutine 1237 [running]:
Feb 15 15:13:15 flexengine virtengine[18899]: github.com/megamsys/vertice/provision/docker/cluster.(*Cluster).SetNetworkinNode(0xc4201ae7e0, 0xc4203ac380, 0xa, 0xc420516fa0, 0x16, 0xc4205acf60, 0x10, 0xbb3840, 0xc420400370)
Feb 15 15:13:15 flexengine virtengine[18899]: /home/jonathan/.go/src/github.com/megamsys/vertice/provision/docker/cluster/container.go:320 +0x90
Feb 15 15:13:15 flexengine virtengine[18899]: github.com/megamsys/vertice/provision/docker/container.(*Container).NetworkInfo(0xc4204e5b80, 0x130cfe0, 0xc42012cb10, 0x0, 0x0, 0xc4203a9f38, 0x42b20e, 0xc400000008, 0xc4203242c0)
Feb 15 15:13:15 flexengine virtengine[18899]: /home/jonathan/.go/src/github.com/megamsys/vertice/provision/docker/container/container.go:382 +0xc3
Feb 15 15:13:15 flexengine virtengine[18899]: github.com/megamsys/vertice/provision/docker.(*dockerProvisioner).Start.func1(0xc4204e5b80, 0xc42033a120, 0xc4204752c0, 0x0)
Feb 15 15:13:15 flexengine virtengine[18899]: /home/jonathan/.go/src/github.com/megamsys/vertice/provision/docker/provisioner.go:246 +0xf5
Feb 15 15:13:15 flexengine virtengine[18899]: github.com/megamsys/vertice/provision/docker.runInContainers.func1(0x0, 0x1, 0x0, 0x0)
Feb 15 15:13:15 flexengine virtengine[18899]: /home/jonathan/.go/src/github.com/megamsys/vertice/provision/docker/actions.go:70 +0xd1
Feb 15 15:13:15 flexengine virtengine[18899]: created by github.com/megamsys/vertice/provision/docker.runInContainers
Feb 15 15:13:15 flexengine virtengine[18899]: /home/jonathan/.go/src/github.com/megamsys/vertice/provision/docker/actions.go:85 +0x206

**Comment by vijaykanthm28** [comment]
fixed #404
