### ISSUE TITLE
Duplicate events shows is UI

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#406]
![image](https://cloud.githubusercontent.com/assets/18652643/23151953/92245fb2-f824-11e6-9b93-2b93251682d6.png)
![image](https://cloud.githubusercontent.com/assets/18652643/23151970/a4e5c848-f824-11e6-9d3e-410fe347dfa4.png)

**Comment by vijaykanthm28** [comment]
issue replicated to https://gitlab.com/megamsys/nilavu/issues/1182
