### ISSUE TITLE
Backup delete is not work

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#407]
**Vertice** received the request

Feb 22 05:28:13 master virtengine[13468]: time="2017-02-22T05:28:13Z" level=debug msg="vms queue received message  :{"name":"weathered-glade-1091.raid1.host","cat_id":"BAK6290081618384466944","cattype":"torpedo","id":"RIP6835826322051829017","account_id":"info@megam.io","category":"backup","action":"backupremove"}"

Can you verify this is correct..?

**Comment by vijaykanthm28** [comment]
but action:  "backupdestroy" in vertice

**Comment by vijaykanthm28** [comment]
fixed
