### ISSUE TITLE
CUST: Vertice panic "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vertice#408]
Vertice panic so stopped automatically.. user can't launch VM's..

Feb 28 21:16:02 ubuntu virtengine[5131]: time="2017-02-28T21:16:02+01:00" level=debug msg="  => step 4: destroy-old-route action"
Feb 28 21:16:02 ubuntu virtengine[5131]: time="2017-02-28T21:16:02+01:00" level=debug msg="route53 ready"
Feb 28 21:16:02 ubuntu virtengine[5131]: time="2017-02-28T21:16:02+01:00" level=debug msg="dry-sea-7512.atominstance.com_log:{28 Feb 17 21:16 C
Feb 28 21:16:02 ubuntu virtengine[5131]: ERR  1205 (146.0.247.2:4150) IO error - EOF
Feb 28 21:16:02 ubuntu virtengine[5131]: time="2017-02-28T21:16:02+01:00" level=debug msg="dry-sea-7512.atominstance.com_log:{28 Feb 17 21:16 C
Feb 28 21:16:02 ubuntu virtengine[5131]: ERR  1206 (146.0.247.2:4150) IO error - EOF
Feb 28 21:16:02 ubuntu virtengine[5131]: time="2017-02-28T21:16:02+01:00" level=debug msg="dry-sea-7512.atominstance.com_log:{28 Feb 17 21:16 C
Feb 28 21:16:02 ubuntu virtengine[5131]: ERR  1207 (146.0.247.2:4150) IO error - EOF
Feb 28 21:16:12 ubuntu virtengine[5131]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 28 21:16:12 ubuntu virtengine[5131]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x982ec6]
Feb 28 21:16:12 ubuntu virtengine[5131]: goroutine 108218 [running]:
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/karlentwistle/route53.getBody(0xd89a9b, 0x40, 0xc420d7e840, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/karlentwistle/route53/route53.go:71 +0x166
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/karlentwistle/route53.(*AccessIdentifiers).zoneXML(0xc420d95d20, 0xd89a9b, 0x40, 0x1d, 0xc4
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/karlentwistle/route53/access_identifiers.go:57 +0x51
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/karlentwistle/route53.(*AccessIdentifiers).Zones(0xc420d95d20, 0xc42011aaf0, 0x10, 0x0)
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/karlentwistle/route53/access_identifiers.go:49 +0x58
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/vertice/router/route53.(*route53Router).zoneMatch(0xc420d95d00, 0x1d, 0xc420c6eaa0
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/megamsys/vertice/router/route53/router.go:150 +0x7e
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/vertice/router/route53.route53Router.UnsetCName(0x0, 0x0, 0x0, 0x0, 0xc420250700, 
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/megamsys/vertice/router/route53/router.go:73 +0xbc
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/vertice/router/route53.(*route53Router).UnsetCName(0xc420d95c80, 0xc420c6eaa0, 0x1
Feb 28 21:16:12 ubuntu virtengine[5131]:         <autogenerated>:2 +0xb4
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/vertice/provision/one.glob..func29(0xd35120, 0xc4208cfd40, 0xc4220cfd70, 0x1, 0x1,
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/megamsys/vertice/provision/one/actions.go:477 +0x31e
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/libgo/action.(*Pipeline).Execute(0xc420c6e760, 0xc4220cfd70, 0x1, 0x1, 0x7, 0xc421
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/megamsys/libgo/action/action.go:147 +0x7a0
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/vertice/provision/one.(*oneProvisioner).Destroy(0xc4201c2140, 0xc4200bf180, 0x132c
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/megamsys/vertice/provision/one/provisioner.go:302 +0x3e9
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/vertice/carton.Destroy(0xc421633b68, 0x0, 0x0)
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/destroyer.go:24 +0x268
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/vertice/carton.(*Carton).Destroy(0xc4228c5800, 0x33, 0x0)
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/carton.go:119 +0xe7
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/vertice/carton.DestroyProcess.Process(0xc421508340, 0x16, 0xc42053a080, 0x1, 0x1, 
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/megd_process.go:58 +0x48
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/vertice/carton.(*DestroyProcess).Process(0xc42258c000, 0xc42053a080, 0x1, 0x1, 0x0
Feb 28 21:16:12 ubuntu virtengine[5131]:         <autogenerated>:5 +0x74
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/vertice/carton.(*ReqOperator).Accept(0xc420394f60, 0xc421633f20, 0xc42258c000, 0x0
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/megamsys/vertice/carton/req_operator.go:44 +0x15b
Feb 28 21:16:12 ubuntu virtengine[5131]: github.com/megamsys/vertice/subd/deployd.(*Handler).serveNSQ(0xc42026b080, 0xc420f26300, 0x0, 0x0)
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/megamsys/vertice/subd/deployd/handler.go:24 +0x10c
Feb 28 21:16:12 ubuntu virtengine[5131]: created by github.com/megamsys/vertice/subd/deployd.(*Service).processNSQ
Feb 28 21:16:12 ubuntu virtengine[5131]:         /home/jonathan/.go/src/github.com/megamsys/vertice/subd/deployd/service.go:77 +0x17f
Feb 28 21:16:12 ubuntu systemd[1]: virtengine.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 28 21:16:12 ubuntu systemd[1]: virtengine.service: Unit entered failed state.
Feb 28 21:16:12 ubuntu systemd[1]: virtengine.service: Failed with result 'exit-code'.
Mar 01 05:14:21 ubuntu systemd[1]: Started virtengine core engine - Omni scheduler..
Mar 01 05:14:21 ubuntu virtengine[47440]: time="2017-03-01T05:14:21+01:00" level=info msg=vertice.

**Comment by vijaykanthm28** [comment]
Its duplicate issue and related to  #200
